/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Metodos.FormReglaFalsa;
import Metodos.FormBiseccion;
import Metodos.FormNewton;
import Metodos.FormRaicesMultiples;
import Metodos.FormSecante;
import java.awt.Dimension;
import javax.swing.JInternalFrame;

/**
 *
 * @author eroda
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VentanaHome = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        SubMenuInformacion = new javax.swing.JMenuItem();
        SubMenuSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        SubMenuNewton = new javax.swing.JMenuItem();
        SubMenuSecante = new javax.swing.JMenuItem();
        SubMenuRaicesMultiples = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        SubMenuBiseccion = new javax.swing.JMenuItem();
        SubMenuReglaFalsa = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        setTitle("PRINCIPAL METODOS NUMERICOS");

        javax.swing.GroupLayout VentanaHomeLayout = new javax.swing.GroupLayout(VentanaHome);
        VentanaHome.setLayout(VentanaHomeLayout);
        VentanaHomeLayout.setHorizontalGroup(
            VentanaHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 591, Short.MAX_VALUE)
        );
        VentanaHomeLayout.setVerticalGroup(
            VentanaHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 364, Short.MAX_VALUE)
        );

        getContentPane().add(VentanaHome, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Ayuda");

        SubMenuInformacion.setText("Informacion");
        SubMenuInformacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubMenuInformacionActionPerformed(evt);
            }
        });
        jMenu1.add(SubMenuInformacion);

        SubMenuSalir.setText("Salir");
        SubMenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubMenuSalirActionPerformed(evt);
            }
        });
        jMenu1.add(SubMenuSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Metodo Abierto");

        SubMenuNewton.setText("Newton");
        SubMenuNewton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubMenuNewtonActionPerformed(evt);
            }
        });
        jMenu2.add(SubMenuNewton);

        SubMenuSecante.setText("Secante");
        SubMenuSecante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubMenuSecanteActionPerformed(evt);
            }
        });
        jMenu2.add(SubMenuSecante);

        SubMenuRaicesMultiples.setText("Raíces Multiples");
        SubMenuRaicesMultiples.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubMenuRaicesMultiplesActionPerformed(evt);
            }
        });
        jMenu2.add(SubMenuRaicesMultiples);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Metodo Cerrado");

        SubMenuBiseccion.setText("Biseccion");
        SubMenuBiseccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubMenuBiseccionActionPerformed(evt);
            }
        });
        jMenu3.add(SubMenuBiseccion);

        SubMenuReglaFalsa.setText("Regla Falsa");
        SubMenuReglaFalsa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubMenuReglaFalsaActionPerformed(evt);
            }
        });
        jMenu3.add(SubMenuReglaFalsa);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Raices de Polinomios");

        jMenuItem6.setText("Muller");
        jMenu4.add(jMenuItem6);

        jMenuItem7.setText("Bairstow");
        jMenu4.add(jMenuItem7);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubMenuBiseccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubMenuBiseccionActionPerformed
        FormBiseccion formBiseccion = new FormBiseccion();
        CentrarForm(formBiseccion);
    }//GEN-LAST:event_SubMenuBiseccionActionPerformed

    private void SubMenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubMenuSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SubMenuSalirActionPerformed

    private void SubMenuReglaFalsaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubMenuReglaFalsaActionPerformed
        FormReglaFalsa formReglaFalsa = new FormReglaFalsa();
        CentrarForm(formReglaFalsa);
    }//GEN-LAST:event_SubMenuReglaFalsaActionPerformed

    private void SubMenuSecanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubMenuSecanteActionPerformed
        FormSecante formSecante = new FormSecante();
        CentrarForm(formSecante);
    }//GEN-LAST:event_SubMenuSecanteActionPerformed

    private void SubMenuNewtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubMenuNewtonActionPerformed
        FormNewton formNewton = new FormNewton();
        CentrarForm(formNewton);
    }//GEN-LAST:event_SubMenuNewtonActionPerformed

    private void SubMenuRaicesMultiplesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubMenuRaicesMultiplesActionPerformed
        FormRaicesMultiples formRaicesMultiples = new FormRaicesMultiples();
        CentrarForm(formRaicesMultiples);
    }//GEN-LAST:event_SubMenuRaicesMultiplesActionPerformed

    private void SubMenuInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubMenuInformacionActionPerformed
       InfoPrograma infoPrograma = new InfoPrograma();
        CentrarForm(infoPrograma);
    }//GEN-LAST:event_SubMenuInformacionActionPerformed

    public void CentrarForm(JInternalFrame frame){
        VentanaHome.add(frame);
        Dimension dimension = VentanaHome.getSize();
        Dimension dimensionF = frame.getSize();
        frame.setLocation((dimension.width - dimensionF.width)/2, (dimension.height - dimensionF.height)/2);
        frame.show();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem SubMenuBiseccion;
    private javax.swing.JMenuItem SubMenuInformacion;
    private javax.swing.JMenuItem SubMenuNewton;
    private javax.swing.JMenuItem SubMenuRaicesMultiples;
    private javax.swing.JMenuItem SubMenuReglaFalsa;
    private javax.swing.JMenuItem SubMenuSalir;
    private javax.swing.JMenuItem SubMenuSecante;
    public static javax.swing.JDesktopPane VentanaHome;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    // End of variables declaration//GEN-END:variables
}
